# rustfmt doc - https://rust-lang.github.io/rustfmt/

hard_tabs = false
edition = "2021"
max_width = 120
tab_spaces = 2

# unstable_feature = true
indent_style = "Visual"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
condense_wildcard_suffixes = true
fn_params_layout = "Tall"
normalize_comments = true
use_try_shorthand = true
use_small_heuristics = "Max"
