[ultimate]
pwd_key = "vg6MZf]4u%GKv-jThu&HC7,,}#yoX4lGxeNz7E]({v8-a@;="
pwd_token_duration_sec = 86400
token_key = "kiCLCqin54w2eDF-unFn4BrrW;~IJgN.U|-K}g/XP+.$GQQH"
token_duration_sec = 7200

[ultimate.app]
run_mode = "DEV"
name = "qinling-iam"

[ultimate.db]
enable = true
url = "postgres://qinling:2024.Qinling@localhost:55432/qinling"

[ultimate.trace]
enable = true
target = false
log_level = "DEBUG"
log_writer = "Console"
log_dir = "./logs/"

[ultimate.web]
enable = true
server_addr = "127.0.0.1:9500"

[ultimate.grpc]
enable = false
server_addr = "127.0.0.1:9501"
plaintext = true

[ultimate.grpc.clients.qinling-iam]
addr = "http://127.0.0.1:9501"
plaintext = true
