[ultimate.app]
run_mode = "DEV"
name = "app-example"

[ultimate.security.pwd]
expires_in = 604800
default_pwd = "2024.Ultimate"

[ultimate.web]
enable = true
server_addr = "0.0.0.0:8888"

[ultimate.db]
enable = true
host = "localhost"
port = 15432
database = "ultimate"
username = "ultimate"
password = "2024.Ultimate"
