# 设置运行 cargo 时的系统环境变量
[env]
RUST_LOG = "info,tower_http=debug,ultimate=debug,ultimate_common=debug"

[alias]
clippy-all = "clippy --all-features -- -D warnings"
check-all = "check --all-features"

# 设置 rustc 编译器参数
# [build]
# rustflags = ["--cfg", "uuid_unstable"]
