[package]
name = "weixin-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
